apiVersion: v1
kind: Service
metadata:
  name: {{ include "cvx-redis.fullname" . }}
  labels:
    {{- include "cvx-redis.serverLabels" . | nindent 4 }}
    networking.converix.io/vlan: {{ .Values.service.vlan }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "cvx-redis.serverSelectorLabels" . | nindent 4 }}
