apiVersion: v1
kind: Service
metadata:
  name: {{ include "cvx-nodered.fullname" . }}
  labels:
    {{- include "cvx-nodered.labels" . | nindent 4 }}
    networking.converix.io/vlan: {{ .Values.service.vlan }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cvx-nodered.selectorLabels" . | nindent 4 }}
